version: '3'

services:
  lilac:
    image: iredium/lilac/web:latest
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "999k"
    networks:
      - iredium_services

networks:
  iredium_services:
    external: true
